### ISSUE TITLE
Failed to write memory at 0x08000000 [CYT2B75]

### ISSUE THREAD

**Issue by katcoo** [Infineon/openocd#10]
I have successfully installed OpenOCD to my Vmware virtual machine according to the documentation, using the ubuntu16.04 system，Use J-link to connect to my CYT2B75 chip normally, and execute commands such as "reset, halt", etc.

But I encountered a problem when I tried to flash the hex file to CYT2B75,my steps are as follows:
- Execute in terminal 1
~~~shell
openocd -s /opt/openocd_cyp_4.3/openocd/scripts -f interface/jlink.cfg -f target/psoc6_512k.cfg -c "targets psoc6.cpu.cm4;target current"
~~~
After the execution is complete, the output information is as follows：
~~~shell
Open On-Chip Debugger 0.10.0+dev-4.2.0.1430 (2021-03-05-16:30)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 2000 kHz
adapter srst delay: 25
adapter srst pulse_width: 25
** Test Mode acquire not supported by selected adapter
cortex_m reset_config sysresetreq
cortex_m reset_config sysresetreq
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : J-Link V9 compiled Feb  2 2021 16:34:10
Info : Hardware version: 9.40
Info : VTarget = 3.295 V
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x6ba02477
Info : psoc6.cpu.cm0: hardware has 4 breakpoints, 2 watchpoints
***************************************
** Silicon: 0x0000, Family: 0x252, Rev.: 0x10 (A*)
** Device is not present in the UDD
Error: Unsupported Flash Boot Version - Flash Boot Version [31:28] = 15
** Chip Protection: NORMAL
***************************************
Info : psoc6.cpu.cm4: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for psoc6.cpu.cm0 on 3333
Info : Listening on port 3333 for gdb connections
Info : starting gdb server for psoc6.cpu.cm4 on 3334
Info : Listening on port 3334 for gdb connections
~~~
- Execute in terminal 2
~~~shell
telnet localhost 4444
~~~
Execute programming commands：
~~~shell
flash write_image erase /home/code/app_CYT2B75CM4.hex
~~~
The output information is as follows:
~~~shell
> flash write_image erase /home/code/app_CYT2B75CM4.hex
auto erase enabled
Probed Flash Bank @0x10000000, size 1088.0 KiB (in 17 steps)
Padding image section 0 at 0x1003dc48 with 440 bytes (bank write end alignment)
SWD DPIDR 0x6ba02477
Failed to write memory at 0x08000000
failed erasing sectors 128 to 494
~~~
Using the [program] command, similar errors are also prompted：
~~~shell
> program /home/code/app_CYT2B75CM4.hex
SWD DPIDR 0x6ba02477
psoc6.cpu.cm0 halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x000000f8 msp: 0x0801f800
psoc6.cpu.cm0: bkpt @0x10000159, issuing SYSRESETREQ
SWD DPIDR 0x6ba02477
psoc6.cpu.cm0 halted due to debug-request, current mode: Thread 
xPSR: 0x21000000 pc: 0x10000158 msp: 0x08004000
** psoc6.cpu.cm4: Ran after reset and before halt...
psoc6.cpu.cm4 halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x000001bc msp: 0x0801f800
** Programming Started **
auto erase enabled
Padding image section 0 at 0x1003dc48 with 440 bytes (bank write end alignment)
SWD DPIDR 0x6ba02477
Failed to write memory at 0x08000000
failed erasing sectors 128 to 494
embedded:startup.tcl:526: Error: ** Programming Failed **
in procedure 'program' 
in procedure 'program_error' called at file "embedded:startup.tcl", line 591
at file "embedded:startup.tcl", line 526
~~~
I hope you can tell me how to use OpenOCD+J-link to program the CYT2B75 chip correctly, thank you very much.:pray::pray::pray:

**Comment by bohdan-tymkiv** [comment]
Hi @katcoo 

You are using wtong configuration file for the target - CYT2B75 is not a PSoC6-512k device, please use proper configuration file:
`-f target/traveo2_1m_a0.cfg`

The following command line should be sufficient to program the device:
`-f interface/jlink.cfg -f target/traveo2_1m_a0.cfg -c "program /home/code/app_CYT2B75CM4.hex exit"`

Also, I would recommend to use SWD transport instead of JTAG:
`-f interface/jlink.cfg -c "transport select swd" -f target/traveo2_1m_a0.cfg -c "program /home/code/app_CYT2B75CM4.hex exit"`

Bohdan

**Comment by katcoo** [comment]
Hello ~ @bohdan-tymkiv

**Comment by katcoo** [comment]
Hi~ @bohdan-tymkiv 

I followed your suggestion and tried again to download the program to CYT2B75，the operation is normal, program is downloaded to the CYT2B75 chip correctly . :thumbsup::thumbsup::thumbsup:

Thank you very much for your answer, it solved the problem that was bothering me, it's another wonderful day, thank you again for your help and wish you have a nice life.
